services:
  web:
    build:
      context: .
    env_file:
      - .env
      - .env.local

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insite_test
      - FLASK_ENV=testing
      - APP_STAGE=test
      - BASE_URL=http://192.168.1.187:8080
      - PORT=5000 # Match the port we are actually using
      - PUBLIC_BASE_URL=http://192.168.1.187:8080
      - STORAGE_BACKEND=local
      - SERVER_DOMAIN=localhost
      - RUN_MIGRATIONS_ON_STARTUP=true

    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:5000"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insite_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
